[project]
name = "bac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pdfplumber>=0.11.9",
    "progressbar2>=4.5.0",
    "pypdf>=6.6.2",
    "requests>=2.32.5",
]
